Algoritmo "soma dos numeros"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   : Soma numeros pares até 500
// Autor(a)    : Guilherme Farias
// Data atual  : 08/09/2021
Var
   cont, soma: inteiro

Inicio
   enquanto (cont<=20) faca
   se (cont%2=1)  entao
   escreval("O valor ",cont, " é ímpar")
   fimse
   cont<-cont+1
   fimenquanto


Fimalgoritmo