Algoritmo "EX 54"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : soma
// Autor(a)    : Guilherme Farias
// Data atual  : 10/09/2021
Var
   cont,acumulador:inteiro

Inicio
acumulador<-0
   para cont de 1 ate 100 passo 1 faca
   acumulador<-acumulador+cont
   fimpara
   escreval("O resultado é: ",acumulador)
Fimalgoritmo